spring:
  datasource:
    url: jdbc:postgresql://${TASK_MANAGEMENT_DB_HOST}:${TASK_MANAGEMENT_DB_PORT}/${TASK_MANAGEMENT_DB_NAME}
    username: ${TASK_MANAGEMENT_DB_USER}
    password: ${TASK_MANAGEMENT_DB_PASS}
