[versions]
appVersion = "0.1.0-SNAPSHOT"
assertJ = "3.27.6"
auth0Jwt = "4.5.0"
junit = "6.0.2"
lombok = "1.18.42"
mockito = "5.21.0"
springdoc = "3.0.1"

[libraries]
assertJ = { group = "org.assertj", name = "assertj-core", version.ref = "assertJ" }
auth0Jwt = { group = "com.auth0", name = "java-jwt", version.ref = "auth0Jwt" }
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
mockitoJunitJupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
springdoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
