[versions]
appVersion = "0.1.0-SNAPSHOT"
lombok = "1.18.42"
junit = "6.0.1"
springdoc = "3.0.1"

[libraries]
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
springdoc = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
